version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5433"

  identityserver:
    build: .
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:8081"
      - "8441:8441"
    volumes:
      - .:/app
    command: dotnet MyIdentityServer.dll
